apiVersion: v1
data:
  machinegroupprofile_overrides: |
    extern_dynamic: 10.3.0.1/16
    extern_static: 10.4.0.1/16
    fabric_name: k8s-bm-2
    kubeapi_vlan: 101
    mcast_range:
      start: 225.114.1.1
      end: 225.114.255.255
    node_subnet: 1.100.101.1/24
    node_svc_subnet: 10.5.0.1/16
    pod_subnet: 10.2.0.1/16
    service_vlan: 102
kind: ConfigMap
metadata:
  labels:
    cluster: aci-cni
    fabric: on-prem-dev-infra
    site: bldg-15-lab
  name: for-aci-cni
  namespace: netop-manager
